version: "3.9"
services:
  web:
    image: node:16.18.0
    ports:
      - "3030:3030"
    volumes:
      - "../.:/app"
    environment:
      NODE_ENV: DEVELOPMENT
      HOST: 192.168.0.104
    working_dir: /app
    command: sh -c "cd /app; yarn; yarn run vite"